### ISSUE TITLE
Query parameters are dropped by proxy

### ISSUE THREAD

**Issue by EthanYidong** [campbellC/third-wheel#23]
https://github.com/campbellC/third-wheel/blob/9bcff74a08b70d8c5c8577b116ac34676927f262/src/proxy.rs#L73

`Uri::path()` only returns the "path" portion of the URI, but we need to send both the path and the query to the target server.

**Comment by campbellC** [comment]
This PR may have been done before the upgrade of Tokio because it no longer builds. I will revert the merge and then figure out how to do this with the new library version - I'm in the middle of a larger rewrite of the interface for the library so this will be lower priority to fix for now

**Comment by campbellC** [comment]
https://github.com/campbellC/third-wheel/commit/5148a140ff8317715d5ce287c64f951cf4fe179a

I've cleaned up the code in this area to stop doing unwraps. I believe this issue is now sorted and I've added an integration test that witnesses it. Thanks for the bug report, let me know if you run into any further issues.
